name: Run PlatformIO Unit Tests

on:
  push:
    branches:
      - linearAlgebra 
  pull_request:
    branches:
      - linearAlgebra

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Install dependencies
        run: platformio lib install

      - name: Clean build environment
        run: platformio run --target clean

      - name: Run tests on the native platform
        run: platformio test -e native -vvv